spring.application.name=resturant

# Fix: Change 'dataSourse' to 'datasource' and 'urls' to 'url'
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/resturant_db
spring.datasource.username=root
spring.datasource.password=HAzi@1915

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.check-template-location=false

server.port=8081
